### ISSUE TITLE
Testing and training dataset for HO3D

### ISSUE THREAD

**Issue by yilan120** [ZhangCYG/MOHO#1]
Hi, thanks for your work and the release of the code! Also, congratulate on the acceptance of CVPR24!

I've got one question regarding the model evaluation on the HO3D dataset. Are you trained on one case at a time(like ABF14), and then testing on the corresponding cases? Or use all cases in the training set at train stage?

I couldn't find where and how you implement this logic in your code, could you please also point that out?

Thanks!!

**Comment by ZhangCYG** [comment]
No, we follow the training and testing splits of IHOI https://github.com/JudyYe/ihoi. As a generalizable NeRF setting, training is conducted with multiple scenes, and testing is on novel scenes.
