### ISSUE TITLE
No segm and meta files in the SOMVideo_sup/rendered_mv/train

### ISSUE THREAD

**Issue by ZhongqunZHANG** [ZhangCYG/MOHO#2]
Hi,

Thanksss a lot for your awesome work.

When I tried to pre-train your model on SOMVideo_sup, I found there is no sign/ and meta/ in the rendered_mv/train. Whether I need to run some files to generate them? or did you miss uploading these files?

**Comment by ZhangCYG** [comment]
Thanks for the issue. We are checking the released data and will upload the correct version.

**Comment by ZhongqunZHANG** [comment]
Thanks for your reply. If you have updated the data, please let me know. Thanks for help.

**Comment by ZhangCYG** [comment]
We've updated the data and the link is provided in the README file. We've ensured all useful data is completed.
