### ISSUE TITLE
CodaLab error

### ISSUE THREAD

**Issue by cgz6498** [ZhangCYG/MOHO#3]
<img width="359" alt="2854e1980bf883192826f26de42e69b" src="https://github.com/ZhangCYG/MOHO/assets/77420384/339cd58b-d28d-44b4-a51c-251766cd0317">
Hello, I failed to open the View scoring error log when I was verifying on the official website. 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment. warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') You are using pip version 9.0.1, however version 24.0 is available. You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ZhangCYG** [comment]
Sorry, I'm not familiar with this function. But are you using python2.7? I think it may be not compatible with this project.

**Comment by cgz6498** [comment]
No,I use python3.8

**Comment by ZhangCYG** [comment]
What specific file are you running in this repo?

**Comment by cgz6498** [comment]
The generated json file is compressed into zip for submission

**Comment by ZhangCYG** [comment]
For train or test, please be more specific.

**Comment by ZhangCYG** [comment]
Sorry, I don't think our repo used CodaLab. I'd like all the issues to be polite and constructive. I'm not willing to help solve disgraceful problems, for wasting all people's time.
