### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by deepdata-foundation** [ZhangCYG/MOHO#4]
Great work

Could you please share your checkpoint for HO3D and DexYCB(real world fine-tuning)

**Comment by ZhangCYG** [comment]
Sure. I've uploaded the DexYCB checkpoint and the SOMVideo pretrained one. For server maintaining reasons, currently I cannot find the HO3D checkpoint, but HO3D is a relatively small dataset, you can easily use the SOMVideo pretrained checkpoint to finetune on it in a quick period.
