### ISSUE TITLE
Question about  "pose_origin_woinv"

### ISSUE THREAD

**Issue by yuhanglu2000** [ZhangCYG/MOHO#5]
Thank you for your interesting work! I noticed a potential issue in your code related to variable assignment. Could you please take a look?

In models/dexycb_dataset.py, lines 234-235:

```python
pose_all = [torch.inverse(pose) for pose in pose_all]
pose_origin_woinv = [pose.float() for pose in pose_all]
```

It seems that pose_origin_woinv still holds the inversed poses, since pose_all has been reassigned with a different meaning.

A similar issue occurs in models/ho3d_dataset.py, lines 139-140.

**Comment by ZhangCYG** [comment]
Thanks for pointing out. We find it's because the formating issue when tidying the code to release. We have fixed code and updated.
